version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - ./backend/db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=matchcv.settings

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "8080:80"
    depends_on:
      - backend