# Generated by Django 5.2 on 2025-04-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_about_summary_profile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='achievements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='experience',
            name='responsibilities',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
